basePath: /api
definitions:
  requests.PersonRequest:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: formation-go documentation server.git stat
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: formation-go
  version: "1.0"
paths:
  /person:
    post:
      parameters:
      - description: Person body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/requests.PersonRequest'
      responses:
        "200":
          description: OK
swagger: "2.0"
